# Generated by Django 5.0.7 on 2024-09-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Phone',
            new_name='phone',
        ),
    ]
